  ; Script generated by the Inno Setup Script Wizard.
  ; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES

  #define MyAppName "WindowsNJQCA"
  #define MyAppVersion "8.8"
  #define MyAppPublisher "NewJaisa Tehnologies Ltd."
  #define MyAppURL "https://newjaisa.com/"

  [Setup]
  ; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
  ; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
  AppId={{CB664719-0CB5-421D-ABD7-5A0674315607665594}
  AppName={#MyAppName}
  AppVersion={#MyAppVersion}
  ;AppVerName={#MyAppName} {#MyAppVersion}
  AppPublisher={#MyAppPublisher}
  AppPublisherURL={#MyAppURL}
  AppSupportURL={#MyAppURL}
  AppUpdatesURL={#MyAppURL}
  DefaultDirName=C:\{#MyAppName}
  DisableDirPage=yes
  DefaultGroupName={#MyAppName}
  DisableProgramGroupPage=yes
  ; Uncomment the following line to run in non administrative install mode (install for current user only.)
  PrivilegesRequired=lowest
  OutputDir=C:\Users\Administrator\Documents\Windows NJQCA EXE\output
  OutputBaseFilename=WindowsNJQCA_8.8
  SetupIconFile=C:\Users\Administrator\Documents\Windows NJQCA EXE\setup.ico
  Compression=lzma
  SolidCompression=yes
  WizardStyle=modern


  [Languages]
  Name: "english"; MessagesFile: "compiler:Default.isl"

  [Files]
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\update.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\PresentMon-2.4.0-x64.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\django-todo\*"; DestDir: "{app}\django-todo"; Flags: ignoreversion recursesubdirs createallsubdirs
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\Amazon-Clone\*"; DestDir: "{app}\Amazon-Clone"; Flags: ignoreversion recursesubdirs createallsubdirs
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\db\*"; DestDir: "{app}\db"; Flags: ignoreversion recursesubdirs createallsubdirs
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\Hard Disk Sentinel\*"; DestDir: "{app}\Hard Disk Sentinel"; Flags: ignoreversion recursesubdirs createallsubdirs
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\ffmpeg\*"; DestDir: "{app}\ffmpeg"; Flags: ignoreversion recursesubdirs createallsubdirs
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\Geekbench 5\*"; DestDir: "{app}\Geekbench 5"; Flags: ignoreversion recursesubdirs createallsubdirs
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\OpenHardwareMonitor\*"; DestDir: "{app}\OpenHardwareMonitor"; Flags: ignoreversion recursesubdirs createallsubdirs
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\HeavyLoad\*"; DestDir: "{app}\HeavyLoad"; Flags: ignoreversion recursesubdirs createallsubdirs
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\Temp_Data\*"; DestDir: "{app}\Temp_Data\"; Flags: ignoreversion recursesubdirs createallsubdirs
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\cacert.pem"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\NJQCA.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\libcurl-x64.dll"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\sqlite3.dll"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\WinBio.lib"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\blur.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\run_heavy_load.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\AutopilotCheck.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\y-cruncher v0.8.7.9547b\*"; DestDir: "{app}\y-cruncher v0.8.7.9547b"; Flags: ignoreversion recursesubdirs createallsubdirs  
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\runperformance.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\restart.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\web_scrap.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\screen_record.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\performance.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\slmgr.vbs"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\fingerprint.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\BlueScreenView.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\fingerprint.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\audio_similarity.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\ardunio.exe"; DestDir: "{app}"; Flags: ignoreversion
  ;Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\Setup.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\office_installer.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\NJCare.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\performance_monitor.exe"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\wifitest.xml"; DestDir: "{app}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\RunNJQCA.bat"; DestDir: "{userdesktop}"; Flags: ignoreversion
  Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\run_njqca.bat"; DestDir: "{app}"; Flags: ignoreversion
  ;Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\lENOVO FTDI-FORCED-10x64-2.12.36.20-drp\*"; DestDir: "{app}\Common"; Flags: ignoreversion recursesubdirs createallsubdirs
  ;Source: "C:\Users\Administrator\Documents\Windows NJQCA EXE\Serial\*"; DestDir: "{app}\Serial"; Flags: ignoreversion recursesubdirs createallsubdirs

  ; NOTE: Don't use "Flags: ignoreversion" on any shared system files

  [UninstallRun]
  ; Uninstall Hard Disk Sentinel in Task Schedule with elevated privileges (run as admin)
  Filename: "cmd.exe"; Parameters: "/c start /min ""{app}\Hard Disk Sentinel\removehds7.vbs"""; Flags: runascurrentuser waituntilterminated; RunOnceId: "Uninstall_HardDiskSentinel"

  ; Delete all files in the app directory (without needing additional confirmation)
  Filename: "cmd.exe"; Parameters: "/c rd /s /q ""{app}"""; Flags: runascurrentuser waituntilterminated; RunOnceId: "UninstallAppFiles"

  ; Remove the RunNJQCA batch file shortcut from the desktop
  Filename: "cmd.exe"; Parameters: "/c del /f /q ""{userdesktop}\RunNJQCA.bat"""; Flags: runascurrentuser waituntilterminated; RunOnceId: "UninstallShortcut"